In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf 
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import keras as keras
from keras import models
from keras import layers
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD
from keras.utils.np_utils import to_categorical
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.neural_network import MLPClassifier
from keras import metrics
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.preprocessing import LabelBinarizer

Using TensorFlow backend.


In [2]:
red = pd.read_csv('data/winequality-red1.csv')
white = pd.read_csv('data/winequality-white1.csv')

In [3]:
red['quality'].replace(to_replace=[0,1,2,3,4,5], value=1, inplace=True)
red['quality'].replace(to_replace=[6], value=2, inplace=True)
red['quality'].replace(to_replace=[7,8,9,10], value=3, inplace=True)
X_red = red[
['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol']]
Y_red = red[['quality']]
white['quality'].replace(to_replace=[0,1,2,3,4,5], value=1, inplace=True)
white['quality'].replace(to_replace=[6], value=2, inplace=True)
white['quality'].replace(to_replace=[7,8,9,10], value=3, inplace=True)
X_white = white[
['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol']]

Y_white = white[['quality']]
X_red = X_red.values
Y_red = Y_red.values
X_white = X_white.values
Y_white = Y_white.values
number_of_features = 11

In [10]:
def rsme(targets, outputs):
    return tf.sqrt(tf.reduce_mean(tf.square(tf.subtract(targets, outputs))))  

# Create function returning a compiled network
def create_network():
    
    # Start neural network
    network = models.Sequential()

    network.add(layers.Dense(units=12, activation='relu', input_shape=(number_of_features,)))
    network.add(layers.Dense(units=30, activation='relu', input_shape=(number_of_features,)))
    network.add(layers.Dense(units=4, activation='relu', input_shape=(number_of_features,)))
    network.add(layers.Dense(units=6, activation='relu', input_shape=(number_of_features,)))
    network.add(layers.Dense(units=12, activation='relu', input_shape=(number_of_features,)))
    network.add(layers.Dense(units=20, activation='relu', input_shape=(number_of_features,)))
    network.add(layers.Dense(units=42, activation='relu', input_shape=(number_of_features,)))
    network.add(layers.Dense(units=5, activation='relu', input_shape=(number_of_features,)))
    network.add(layers.Dense(units=3, activation='relu', input_shape=(number_of_features,)))
    network.add(layers.Dense(units=5, activation='relu', input_shape=(number_of_features,)))
    network.add(layers.Dense(units=4, activation='relu', input_shape=(number_of_features,)))
    network.add(layers.Dense(units=4, activation='relu', input_shape=(number_of_features,)))
    network.add(layers.Dense(units=4, activation='relu', input_shape=(number_of_features,)))
    #network.add(layers.Dense(units=10, activation='sigmoid'))
    
    network.add(layers.Dense(3, activation='softmax'))

    # Compile neural network
    #network.compile(loss='binary_crossentropy', # Cross-entropy
   #                 optimizer='rmsprop', # Root Mean Square Propagation
    #                metrics=['accuracy']) # Accuracy performance metric
    network.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy', rsme])
    
    # Return compiled network
    return network

In [5]:
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score

scoring = {'accuracy' : make_scorer(accuracy_score), 
           'precision' : make_scorer(precision_score),
           'recall' : make_scorer(recall_score), 
           'f1_score' : make_scorer(f1_score)}

In [6]:
neural_network = KerasClassifier(build_fn=create_network, 
                                 epochs=10, 
                                 batch_size=100, 
                                 verbose=0)

In [7]:
#score = ['accuracy', 
           #'precision',
           #'recall', 
           #'f1_score']
#cross_val_score(neural_network, X_train, y_train, cv=7, scoring=score)
    

IndentationError: unexpected indent (<ipython-input-7-a719aab9bc5e>, line 2)

In [12]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
y_train = np.array([number[0] for number in lb.fit_transform(Y_red)])
X_train = X_red

recall = cross_val_score(neural_network, X_train, y_train, cv=5, scoring='recall')
print('Recall', np.mean(recall), recall)
precision = cross_val_score(neural_network, X_train, y_train, cv=5, scoring='precision')
print('Precision', np.mean(precision), precision)
f1 = cross_val_score(neural_network, X_train, y_train, cv=5, scoring='f1')
print('F1', np.mean(f1), f1)

Recall 0.48788293158940643 [0.45641026 0.74193548 0.43195266 0.3814433  0.42767296]
Precision 0.6577557629302676 [0.87878788 0.50609756 0.77777778 0.45303867 0.67307692]
F1 0.49868988030470884 [0.77511962 0.55335968 0.42918455 0.31205674 0.42372881]


In [13]:
cross_val_score(neural_network, X_red, Y_red, cv=10) #relu  #scoring=make_scorer(f1_score(average='weighted'))

array([0.61875001, 0.575     , 0.39999999, 0.49374999, 0.55      ,
       0.4       , 0.46875   , 0.52500001, 0.55624998, 0.42767295])

In [106]:
cross_val_score(neural_network, X_white, Y_white, cv=10) #relu

array([0.45306122, 0.44489796, 0.46938775, 0.41632653, 0.5367347 ,
       0.46734694, 0.48979591, 0.45306123, 0.50102248, 0.61349693])

In [109]:
cross_val_score(neural_network, X_red, Y_red, cv=10) #sigmoid

array([0.71250002, 0.575     , 0.45625001, 0.4625    , 0.625     ,
       0.36875001, 0.39374999, 0.47499999, 0.65624999, 0.47169812])

In [111]:
cross_val_score(neural_network, X_white, Y_white, cv=10) #sogmoid

array([0.45510204, 0.45510205, 0.45102041, 0.50408163, 0.52653061,
       0.42244898, 0.45306122, 0.49183674, 0.58077709, 0.58895704])

In [115]:
cross_val_score(neural_network, X_red, Y_red, cv=10) #tanh

array([0.76250001, 0.58749999, 0.53749999, 0.44999999, 0.61875001,
       0.3625    , 0.425     , 0.45      , 0.64375002, 0.49685535])

In [118]:
cross_val_score(neural_network, X_white, Y_white, cv=10) #tanh

array([0.45510205, 0.47959183, 0.44897959, 0.50408163, 0.54693877,
       0.41020408, 0.48979592, 0.50612245, 0.58486708, 0.55623721])